services:
    prometheus:
        image: prom/prometheus:v2.43.0
        container_name: prometheus
        hostname: prometheus
        restart: unless-stopped
        ports:
          - 9090:9090
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
          - prometheus:/prometheus

    jaeger:
        image: jaegertracing/all-in-one:1.54
        container_name: jaeger
        hostname: jaeger
        restart: unless-stopped
        environment:
            - COLLECTOR_OTLP_ENABLED=true
        ports:
            - 6831:6831/udp # Thrift-compact protocol (agent)
            - 6832:6832/udp # Thrift-binary protocol (agent)
            - 5778:5778 # serve configs (agent)
            - 16686:16686 # Jaeger UI (query)
            - 4317:4317 # OTLP over gRPC (collector)
            - 4318:4318 # OTLP over HTTP (collector)
            - 14250:14250 # model.proto (collector)
            - 14268:14268 # jaeger.thrift directly from clients (collector)
            - 14269:14269 # metrics scraping endpoint (collector)
            - 9411:9411 # Zipkin compatible endpoint (collector)

    grafana:
        image: grafana/grafana:9.4.7
        container_name: grafana
        hostname: grafana
        environment:
          - GF_AUTH_ANONYMOUS_ENABLED=true
          - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
          - GF_AUTH_DISABLE_LOGIN_FORM=true
          - GF_USERS_DEFAULT_THEME=light
        volumes:
          - /etc/localtime:/etc/localtime:ro
          - grafana:/var/lib/grafana
        restart: unless-stopped
        user: root
        ports:
          - 3000:3000
        depends_on:
          - prometheus
          - jaeger

volumes:
    prometheus:
    grafana: